import { NextResponse } from 'next/server'

interface IAnimalImage {
	id: number
	name: string
	image: string
	type: string
	category: string
	date: string
	tags: string[]
	location: string
	size: 'маленький' | 'средний' | 'большой' | 'огромный'
	color: string
	diet: 'хищник' | 'травоядное' | 'всеядное' | 'насекомоядное'
	habitat: string
	group?: string
}

const animals: IAnimalImage[] = [
	{
		id: 1,
		name: 'Африканский лев',
		image:
			'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Lion_waiting_in_Namibia.jpg/600px-Lion_waiting_in_Namibia.jpg',
		type: 'african-lion',
		category: 'animals',
		date: '2024-03-15',
		tags: ['млекопитающие', 'хищники', 'саванна', 'африка', 'большие кошки'],
		location: 'Саванна, Африка',
		size: 'большой',
		color: 'золотистый',
		diet: 'хищник',
		habitat: 'саванна',
		group: 'кошачьи',
	},
	{
		id: 2,
		name: 'Бенгальский тигр',
		image:
			'https://www.morningchronicle.co.uk/media/shared/articles/86/47/69/Trio-of-rare-tiger-cubs-spotted-in--107242.jpg',
		type: 'bengal-tiger',
		category: 'animals',
		date: '2024-03-10',
		tags: ['млекопитающие', 'хищники', 'джунгли', 'азия', 'большие кошки'],
		location: 'Джунгли, Индия',
		size: 'большой',
		color: 'оранжевый с черными полосами',
		diet: 'хищник',
		habitat: 'джунгли',
		group: 'кошачьи',
	},
	{
		id: 3,
		name: 'Африканский слон',
		image:
			'https://img.freepik.com/premium-photo/african-elephant-stands-pulling-grass-from-shallows_1048944-30069477.jpg?semt=ais_hybrid&w=740',
		type: 'african-elephant',
		category: 'animals',
		date: '2024-03-05',
		tags: ['млекопитающие', 'травоядные', 'саванна', 'африка', 'крупные животные'],
		location: 'Саванна, Африка',
		size: 'огромный',
		color: 'серый',
		diet: 'травоядное',
		habitat: 'саванна',
		group: 'хоботные',
	},
	{
		id: 4,
		name: 'Большая панда',
		image:
			'https://зеленоград-инфо.рф/wp-content/uploads/2024/03/8847d1bc59afaf314d93f6a4784e6e2c.jpg',
		type: 'giant-panda',
		category: 'animals',
		date: '2024-02-28',
		tags: ['млекопитающие', 'травоядные', 'бамбуковые леса', 'китай'],
		location: 'Горы, Китай',
		size: 'большой',
		color: 'черно-белый',
		diet: 'травоядное',
		habitat: 'бамбуковые леса',
		group: 'медвежьи',
	},
	{
		id: 5,
		name: 'Полярный медведь',
		image:
			'https://assets2.cbsnewsstatic.com/hub/i/r/2025/10/10/1e0e79a7-cf41-41bd-b69d-7412ed388564/thumbnail/640x360/2e37ff4662878c03821557438b08e381/astra-the-polar-bear.jpg',
		type: 'polar-bear',
		category: 'animals',
		date: '2024-02-20',
		tags: ['млекопитающие', 'хищники', 'арктика', 'холодные регионы'],
		location: 'Арктика',
		size: 'большой',
		color: 'белый',
		diet: 'хищник',
		habitat: 'арктика',
		group: 'медвежьи',
	},
	{
		id: 6,
		name: 'Жираф',
		image: 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/1f/da/44.jpg',
		type: 'giraffe',
		category: 'animals',
		date: '2024-02-15',
		tags: ['млекопитающие', 'травоядные', 'саванна', 'длинная шея'],
		location: 'Саванна, Африка',
		size: 'огромный',
		color: 'оранжевый с коричневыми пятнами',
		diet: 'травоядное',
		habitat: 'саванна',
		group: 'жирафовые',
	},
	{
		id: 7,
		name: 'Зебра',
		image: 'https://cdn.telegram-store.com/channels/factorio-facts/469-2024-07-14-1-.jpg',
		type: 'zebra',
		category: 'animals',
		date: '2024-02-10',
		tags: ['млекопитающие', 'травоядные', 'саванна', 'полосатые'],
		location: 'Саванна, Африка',
		size: 'большой',
		color: 'черно-белый полосатый',
		diet: 'травоядное',
		habitat: 'саванна',
		group: 'лошадиные',
	},
	{
		id: 8,
		name: 'Горилла',
		image:
			'https://img.freepik.com/premium-photo/powerful-silverback-gorilla-standing-tall-natural-habitat_1070374-750.jpg',
		type: 'gorilla',
		category: 'animals',
		date: '2024-02-05',
		tags: ['млекопитающие', 'травоядные', 'джунгли', 'приматы', 'обезьяны'],
		location: 'Джунгли, Центральная Африка',
		size: 'большой',
		color: 'черный',
		diet: 'травоядное',
		habitat: 'джунгли',
		group: 'приматы',
	},
	{
		id: 9,
		name: 'Кенгуру',
		image: 'https://i.pinimg.com/originals/c4/82/99/c482993ecccd7fd1ae2918af7b27f0f5.jpg',
		type: 'kangaroo',
		category: 'animals',
		date: '2024-01-30',
		tags: ['млекопитающие', 'травоядные', 'австралия', 'сумчатые', 'прыгучие'],
		location: 'Австралия',
		size: 'большой',
		color: 'серо-коричневый',
		diet: 'травоядное',
		habitat: 'саванна',
		group: 'сумчатые',
	},
	{
		id: 10,
		name: 'Крокодил',
		image:
			'https://images.theconversation.com/files/470483/original/file-20220623-51187-mpi2xr.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=600&h=400&fit=crop&dpr=1',
		type: 'crocodile',
		category: 'animals',
		date: '2024-01-25',
		tags: ['рептилии', 'хищники', 'реки', 'опасные'],
		location: 'Реки, Африка',
		size: 'большой',
		color: 'зеленый',
		diet: 'хищник',
		habitat: 'реки',
		group: 'рептилии',
	},
	{
		id: 11,
		name: 'Орел',
		image:
			'https://www.brcc.kz/wp-content/uploads/2023/11/%D1%81%D1%82%D1%80250-%D0%BD%D0%B8%D0%B7-768x441.jpg',
		type: 'eagle',
		category: 'animals',
		date: '2024-01-20',
		tags: ['птицы', 'хищники', 'хищные птицы', 'горы'],
		location: 'Горы, Северная Америка',
		size: 'средний',
		color: 'коричневый',
		diet: 'хищник',
		habitat: 'горы',
		group: 'птицы',
	},
	{
		id: 12,
		name: 'Фламинго',
		image:
			'https://avatars.mds.yandex.net/i?id=67666534810524db2459a5bfec86d681_l-5269296-images-thumbs&n=13',
		type: 'flamingo',
		category: 'animals',
		date: '2024-01-15',
		tags: ['птицы', 'травоядные', 'водоплавающие', 'розовые'],
		location: 'Болота, Африка',
		size: 'средний',
		color: 'розовый',
		diet: 'травоядное',
		habitat: 'водоемы',
		group: 'птицы',
	},
	{
		id: 13,
		name: 'Дельфин',
		image:
			'https://img.freepik.com/free-photo/dolphin-jumping-out-water_23-2150884533.jpg?semt=ais_hybrid&w=740',
		type: 'dolphin',
		category: 'animals',
		date: '2024-01-10',
		tags: ['млекопитающие', 'хищники', 'океан', 'умные'],
		location: 'Океан',
		size: 'большой',
		color: 'серый',
		diet: 'хищник',
		habitat: 'океан',
		group: 'китообразные',
	},
	{
		id: 14,
		name: 'Китовая акула',
		image: 'https://divemagazine.com/wp-content/uploads/tubbataha-mmf-simon-pierce-whale-shark.jpg',
		type: 'whale-shark',
		category: 'animals',
		date: '2024-01-05',
		tags: ['рыбы', 'травоядные', 'океан', 'крупные рыбы'],
		location: 'Океан',
		size: 'огромный',
		color: 'серый с белыми пятнами',
		diet: 'травоядное',
		habitat: 'океан',
		group: 'рыбы',
	},
	{
		id: 15,
		name: 'Бабочка Монарх',
		image:
			'https://lgrmag.com/wp-content/uploads/2024/12/U.S.-Fish-and-Wildlife-Service-proposes-protection-for-monarch-butterflies.png',
		type: 'monarch-butterfly',
		category: 'animals',
		date: '2024-01-01',
		tags: ['насекомые', 'травоядные', 'бабочки', 'миграционные'],
		location: 'Северная Америка',
		size: 'маленький',
		color: 'оранжевый с черными полосами',
		diet: 'травоядное',
		habitat: 'луга',
		group: 'насекомые',
	},
	{
		id: 16,
		name: 'Волк',
		image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1KBzcC.img?w=768&h=432&m=6',
		type: 'wolf',
		category: 'animals',
		date: '2023-12-25',
		tags: ['млекопитающие', 'хищники', 'леса', 'стайные'],
		location: 'Леса, Северное полушарие',
		size: 'большой',
		color: 'серый',
		diet: 'хищник',
		habitat: 'леса',
		group: 'собачьи',
	},
	{
		id: 17,
		name: 'Лиса',
		image:
			'https://img.freepik.com/premium-photo/cautious-fox-stopped-edge-forest-autumn-leaves_159160-1582.jpg?semt=ais_hybrid',
		type: 'fox',
		category: 'animals',
		date: '2023-12-20',
		tags: ['млекопитающие', 'хищники', 'леса', 'хитрые'],
		location: 'Леса, Европа',
		size: 'средний',
		color: 'рыжий',
		diet: 'всеядное',
		habitat: 'леса',
		group: 'собачьи',
	},
	{
		id: 18,
		name: 'Еж',
		image:
			'https://ds51-pkgo41.gosuslugi.ru/netcat_files/generated/89/154/906x510/215/a86a78ab6d6d0621561fff36c9b7d498.jpg?crop=0%3A0%3A0%3A0&hash=338f6596dce707cfdcd3b7f1b46574a3&resize_mode=0&wm_m=0',
		type: 'hedgehog',
		category: 'animals',
		date: '2023-12-15',
		tags: ['млекопитающие', 'насекомоядные', 'леса', 'колючие'],
		location: 'Леса, Европа',
		size: 'маленький',
		color: 'коричневый',
		diet: 'насекомоядное',
		habitat: 'леса',
		group: 'насекомоядные',
	},
	{
		id: 19,
		name: 'Пингвин',
		image:
			'https://upload.wikimedia.org/wikipedia/commons/8/82/Manchot_Ad%C3%A9lie_-_Adelie_Penguin.jpg',
		type: 'penguin',
		category: 'animals',
		date: '2023-12-10',
		tags: ['птицы', 'хищники', 'антарктика', 'нелетающие'],
		location: 'Антарктика',
		size: 'средний',
		color: 'черно-белый',
		diet: 'хищник',
		habitat: 'антарктика',
		group: 'птицы',
	},
	{
		id: 20,
		name: 'Змея',
		image: 'https://kubnews.ru/upload/iblock/aed/aede721d1ff8a00da41315253fc7aec7.jpg',
		type: 'snake',
		category: 'animals',
		date: '2023-12-05',
		tags: ['рептилии', 'хищники', 'пустыни', 'ядовитые'],
		location: 'Пустыни, Австралия',
		size: 'средний',
		color: 'коричневый',
		diet: 'хищник',
		habitat: 'пустыни',
		group: 'рептилии',
	},
	{
		id: 21,
		name: 'Черепаха',
		image: 'https://i.pinimg.com/736x/7c/56/3f/7c563ff1fbb9f9f7e310595751b9906d.jpg',
		type: 'turtle',
		category: 'animals',
		date: '2023-11-30',
		tags: ['рептилии', 'травоядные', 'океан', 'долгожители'],
		location: 'Океан',
		size: 'средний',
		color: 'зеленый',
		diet: 'травоядное',
		habitat: 'океан',
		group: 'рептилии',
	},
	{
		id: 22,
		name: 'Белка',
		image:
			'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Squirrel_by_mareckr.jpg/960px-Squirrel_by_mareckr.jpg',
		type: 'squirrel',
		category: 'animals',
		date: '2023-11-25',
		tags: ['млекопитающие', 'травоядные', 'леса', 'грызуны'],
		location: 'Леса, Северное полушарие',
		size: 'маленький',
		color: 'рыжий',
		diet: 'травоядное',
		habitat: 'леса',
		group: 'грызуны',
	},
	{
		id: 23,
		name: 'Сова',
		image:
			'https://img.freepik.com/free-photo/view-realistic-owl-day_23-2151357453.jpg?semt=ais_hybrid&w=740',
		type: 'owl',
		category: 'animals',
		date: '2023-11-20',
		tags: ['птицы', 'хищники', 'ночные', 'леса'],
		location: 'Леса, Европа',
		size: 'средний',
		color: 'коричневый',
		diet: 'хищник',
		habitat: 'леса',
		group: 'птицы',
	},
	{
		id: 24,
		name: 'Колибри',
		image:
			'https://img.freepik.com/premium-photo/hummingbird-is-flying-flower-with-flower-foreground_1122950-3804.jpg?semt=ais_hybrid&w=740&q=80',
		type: 'hummingbird',
		category: 'animals',
		date: '2023-11-15',
		tags: ['птицы', 'травоядные', 'маленькие', 'быстрые'],
		location: 'Америка',
		size: 'маленький',
		color: 'разноцветный',
		diet: 'травоядное',
		habitat: 'сады',
		group: 'птицы',
	},
]

export async function GET() {
	return NextResponse.json(animals)
}
